import { eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { offers } from "../../../db/schema";

function num(value: unknown, fallback = 0) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function values(body: Record<string, unknown>) { return { applicationId: num(body.applicationId) || null, company: String(body.company || "").trim(), role: String(body.role || "").trim(), city: String(body.city || "").trim(), baseMonthly: num(body.baseMonthly), salaryMonths: num(body.salaryMonths, 12), annualBonus: num(body.annualBonus), signOn: num(body.signOn), stockAnnual: num(body.stockAnnual), allowanceAnnual: num(body.allowanceAnnual), housingFundRate: num(body.housingFundRate), overtimeScore: num(body.overtimeScore, 3), growthScore: num(body.growthScore, 3), preferenceScore: num(body.preferenceScore, 3), notes: String(body.notes || "").trim() }; }
export async function POST(request: Request) { try { const data = values(await request.json()); if (!data.company) return Response.json({ error: "公司名称不能为空" }, { status: 400 }); const [item] = await getDb().insert(offers).values(data).returning(); return Response.json({ item }, { status: 201 }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "保存失败" }, { status: 500 }); } }
export async function PATCH(request: Request) { try { const body = await request.json() as Record<string, unknown>; const [item] = await getDb().update(offers).set(values(body)).where(eq(offers.id, Number(body.id))).returning(); return Response.json({ item }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "保存失败" }, { status: 500 }); } }
export async function DELETE(request: Request) { try { const id = Number(new URL(request.url).searchParams.get("id")); await getDb().delete(offers).where(eq(offers.id, id)); return Response.json({ ok: true }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "删除失败" }, { status: 500 }); } }
