import { eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { prospects } from "../../../db/schema";

function values(body: Record<string, unknown>) { return { kind: String(body.kind || "目标公司").trim(), company: String(body.company || "").trim(), role: String(body.role || "").trim(), city: String(body.city || "").trim(), tier: String(body.tier || "稳健").trim(), deadlineDate: String(body.deadlineDate || "").trim(), url: String(body.url || "").trim(), reason: String(body.reason || "").trim(), notes: String(body.notes || "").trim() }; }
function duplicateKey(item:{kind:string;company:string;role:string}) { return `${item.kind}\u0000${item.company}\u0000${item.role}`.toLocaleLowerCase("zh-CN"); }
export async function POST(request: Request) { try { const body = await request.json() as Record<string, unknown>; if(Array.isArray(body.items)){const source=body.items.slice(0,500).map(item=>values(item as Record<string,unknown>));const existing=await getDb().select({kind:prospects.kind,company:prospects.company,role:prospects.role}).from(prospects);const seen=new Set(existing.map(duplicateKey));const items=source.filter(item=>{if(!item.company)return false;const key=duplicateKey(item);if(seen.has(key))return false;seen.add(key);return true;});for(let index=0;index<items.length;index+=40)await getDb().insert(prospects).values(items.slice(index,index+40));return Response.json({imported:items.length,skipped:source.length-items.length},{status:201});}const data = values(body); if (!data.company) return Response.json({ error: "公司名称不能为空" }, { status: 400 }); const [item] = await getDb().insert(prospects).values(data).returning(); return Response.json({ item }, { status: 201 }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "保存失败" }, { status: 500 }); } }
export async function PATCH(request: Request) { try { const body = await request.json() as Record<string, unknown>; const [item] = await getDb().update(prospects).set(values(body)).where(eq(prospects.id, Number(body.id))).returning(); return Response.json({ item }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "保存失败" }, { status: 500 }); } }
export async function DELETE(request: Request) { try { const id = Number(new URL(request.url).searchParams.get("id")); await getDb().delete(prospects).where(eq(prospects.id, id)); return Response.json({ ok: true }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "删除失败" }, { status: 500 }); } }
