import { and, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { prospects } from "../../../db/schema";

function values(body: Record<string, unknown>) { return { company: String(body.company || "").trim(), role: String(body.role || "").trim() }; }
function duplicateKey(item:{company:string;role:string}) { return `${item.company}\u0000${item.role}`.toLocaleLowerCase("zh-CN"); }
export async function POST(request: Request) { try { const body = await request.json() as Record<string, unknown>; if(Array.isArray(body.items)){const source=body.items.slice(0,500).map(item=>values(item as Record<string,unknown>));const existing=await getDb().select({company:prospects.company,role:prospects.role}).from(prospects);const seen=new Set(existing.map(duplicateKey));const items=source.filter(item=>{if(!item.company||!item.role)return false;const key=duplicateKey(item);if(seen.has(key))return false;seen.add(key);return true;});for(let index=0;index<items.length;index+=40)await getDb().insert(prospects).values(items.slice(index,index+40));return Response.json({imported:items.length,skipped:source.length-items.length},{status:201});}const data = values(body); if (!data.company||!data.role) return Response.json({ error: "公司名称和岗位名称不能为空" }, { status: 400 }); const [existing] = await getDb().select().from(prospects).where(and(eq(prospects.company,data.company),eq(prospects.role,data.role))).limit(1);if(existing)return Response.json({item:existing,skipped:1});const [item] = await getDb().insert(prospects).values(data).returning(); return Response.json({ item }, { status: 201 }); } catch { return Response.json({ error: "保存失败，请稍后重试。" }, { status: 500 }); } }
export async function PATCH(request: Request) { try { const body = await request.json() as Record<string, unknown>;const data=values(body);if(!data.company||!data.role)return Response.json({error:"公司名称和岗位名称不能为空"},{status:400}); const [item] = await getDb().update(prospects).set(data).where(eq(prospects.id, Number(body.id))).returning(); return Response.json({ item }); } catch { return Response.json({ error: "保存失败，请稍后重试。" }, { status: 500 }); } }
export async function DELETE(request: Request) { try { const id = Number(new URL(request.url).searchParams.get("id")); await getDb().delete(prospects).where(eq(prospects.id, id)); return Response.json({ ok: true }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "删除失败" }, { status: 500 }); } }
